### ISSUE TITLE
Race & ethnicity language

### ISSUE THREAD

**Issue by phiden** [adhocteam/lunchux#45]
Can we modify this to make it easy to read? The language on the [requirements](http://lunchux.devpost.com/details/required_statements) is "these statements must appear in the application as full text," which I interpret as "verbatim," but maybe we can add a friendly-English statement as well?

From Michelle:

This language is hard to understand: "We are required to ask for information about your children's race and ethnicity.
* This information is important and helps to make sure we are fully serving our community. Responding to this section is optional and does not affect your children’s eligibility for free or reduced price meals." Can you just state: "This section is optional. It helps us run the program better when we know who we are serving...."

**Comment by phiden** [comment]
**BOLD** 'decline to answer' and change language to 'I'd rather not say'

**Comment by phiden** [comment]
Duplicated by #87 -- does the language have to be verbatim?

If it is required to use this exact language, use a modal

**Comment by greggersh** [comment]
It is required to be exactly as specified in the rules: http://lunchux.devpost.com/details/required_statements

I think the only thing we should change is that since we are moving this to the end of the application, and it applies to all kids in the household, is making it check all that applies for Ethnicity question.

**Comment by paulsmith** [comment]
This should be addressed by 49bfc4e96c2ce6d7168afd3d21e80b1bbaf5dcf9.
